#!/bin/sh

if [ -z "$2" ]; then
	echo "Not enough arguments"
	exit 0
fi

file=$(readlink -f "$1")
base="${file%.*}"
ext="${file##*.}"

type=""
if [ -n "$3" ]; then
	type="-t ${3}"
fi

# from=""
# if [ -z "$type" ] && [ "$ext" == "md" ]; then
# 	from="-f gfm"
# fi

pandoc $type -s --citeproc -o "${base}.${2}" "$file"
