#!/bin/sh

datefmt="%Y%m%d"
if [ -z $1 ]; then
	fetch=$(date "+%Y%m%d");
else
	date=$(echo $1 | grep -e "[-+][0-9]\+")
	if [ -z $date ]; then
		date=$1
		fetch=$(date -v "+1w" -v "${date}w" "+${datefmt}");
echo $(date -j -f "$datefmt" $fetch "+%A")
	else
		fetch=$(date -v "${date}d" "+${datefmt}");
	fi
fi
echo $(date -j -f "$datefmt" $fetch "+%A")
echo $fetch

subjects="/Users/deangao/.cache/clifesync/subjects.json"
output=$(jq '.data.classes[]' < "$subjects" |
	jq -r '"\(.id); \(.periodName)| \(.room)\t| \(.detailedName)"')
# date; remove empty lines; remove year number; remove W09; lowercase; remove ` - content`
output=$(printf "%s" "$output" |
	sed -E "s/^[0-9]{6}-${fetch}; (.*)/\1/ ;
			/^[0-9]{2}/d ;
			s/^([0-9]\|.*?\|) 9(.*)/\1\2/ ;
			s/W[0-9]{2}// ;
			s/^([0-9]\|.*?\|)(.*)/\1\L\2/
			s/-.*//")

if [ $(echo $output | grep -e "^\s*$" | wc -l) -gt "0" ]; then
	output="do something productive.";
fi
printf "%s\n" "$output"
