#!/bin/sh

file=$(readlink -f "$1")
fil="$1"
dir=${file%/*}
base="${fil%.*}"

cd "$dir" || exit 1

tar -zcf output.tar "$fil" && pien output.tar -q && gzip output.tar && mv output.tar.gz "$base".csv
echo "$fil -> $base.csv"
