#!/bin/sh

base="${1%.*}"

if [ $# -eq 0 ]; then
    echo "No files provided"
    exit 1
fi

gsed "s/^[^\.].*/<p>&<\/p>/g" "$1" | #check for anything not starting with "#", surround with paragraph
gsed "s/^\.sh\s.*/<h2>&<\/h2>/g" | #check for headers
gsed "s/^\.lh\s.*/<h3>&<\/h3>/g" | #surround headers
gsed "s/^\.mh\s.*/<h4>&<\/h4>/g" | #the "&" returns deleted items
gsed "s/\.[^sml].*//g" > "$base.html" #remove "#" from first five statements because it just surrounds

echo "$1 > $base.html"
