#!/bin/sh

if [ $# -eq 0 ]; then
    echo "No files provided"
    exit 1
fi

SH="h2"
LH="h3"
MH="h4"
P="p"
ARGS=""

gsed -i "s/\.[^sml].*//g" "$1"
gsed -i "s/^[^\.]/<p>&/g" "$1"
ex -s +"g/^<$P>/s/$/<\/$P>/g" -cwq "$1"

gsed -i "s/^\.sh\s\"/.sh /g" "$1"
gsed -i "s/^\.sh\s/<$SH>/g" "$1"
ex -s +"g/^<$SH>/s/$/<\/$SH>/g" -cwq "$1"

gsed -i "s/^\.lh\s\"/.lh /g" "$1"
gsed -i "s/^\.lh\s/<$LH>/g" "$1"
ex -s +"g/^<$LH>/s/$/<\/$LH>/g" -cwq "$1"

gsed -i "s/^\.mh\s\"/.mh /g" "$1"
gsed -i "s/^\.mh\s/<$MH>/g" "$1"
ex -s +"g/^<$MH>/s/$/<\/$MH>/g" -cwq "$1"
